source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'GGDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.1'
  pod 'ObjectMapper'

  target 'GGDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GGDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GGNetwork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.1'
  pod 'ObjectMapper'

  target 'GGNetworkTests' do
    inherit! :search_paths
    pod 'Alamofire', '~> 4.1'
    pod 'ObjectMapper'

  end

end
